import Head from 'next/head'
import Link from 'next/link'
import { Comic } from '@/components/Comic'
import useMarvelApi from '../hooks/useMarvelApi'
import styles from '@/styles/Home.module.css'

export default function Home() {
	const comics = useMarvelApi()
	const comicSubset = comics.data?.results
	console.log(comicSubset)
	
	return (
		<div className={styles.container}>
			<Head>
				<title>Exercise 2</title>
				<meta name="description" content="Generated by create next app" />
				<link type="image/x-icon" rel="icon" href="/favicon.ico" />
				
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Comics
				</h1>

				<div className={styles.grid}>
					{/*{comicSubset?.map(({id, title}) => {
						<Comic key={id} comic={title} />
					})}*/}
					
				</div>
			</main>

			<footer className={styles.footer}>
				<p>Data provided by <Link href="http://marvel.com" target="_blank">Marvel</Link>. &copy; 2014 Marvel</p>
			</footer>
		</div>
	)
}
