import Head from 'next/head'
import Link from 'next/link'
import { Comic } from '@/components/Comic'
import styles from '@/styles/Home.module.css'
import md5 from 'blueimp-md5'
const API_PRIVATE = process.env.PRIVATE_API_KEY
const API_PUBLIC = process.env.PUBLIC_API_KEY
const API_URL = process.env.API_URL

export default function Home( comics ) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Exercise 2</title>
				<meta name="description" content="Generated by create next app" />
				<link type="image/x-icon" rel="icon" href="/favicon.ico" />
				
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Comics
				</h1>

				<div className={styles.grid}>
					<Comic key={comics.id} comic={comics} />
					{/*{console.log("$$$$$$$" + comics.comics.data.results.map(comic => comic.id) + "$$$$$$$")}*/}
					{comics.comics.data.results.map((comic) => (
						<Comic key={comic.id} comic={comic} />
					))}
				</div>
			</main>

			<footer className={styles.footer}>
				<p>Data provided by <Link href="http://marvel.com" target="_blank">Marvel</Link>. &copy; 2014 Marvel</p>
			</footer>
		</div>
	)
}

export async function getStaticProps() {
	const timestamp = new Date().toString()
	const unencoded_hash = timestamp + API_PRIVATE + API_PUBLIC
	const auth = md5(unencoded_hash)
	const fetch_url = API_URL + '/v1/public/comics?ts=' + timestamp + '&apikey=' + API_PUBLIC + '&hash=' + auth
	const res = await fetch(fetch_url)
	const comics = await res.json()
	//console.log(comics.data.results);

	return {
		props: { comics },
		revalidate: 1,
	}
}
