import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home( comics ) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Comics
				</h1>

				{comics.comics.map((comic) => (
					<p key={comic.id}>{comic.title}</p>
				))}
				
			</main>

			<footer className={styles.footer}>				
					Copyright 2022, Matthew Waldrop, All Rights Reserved
			</footer>
		</div>
	)
}

export async function getStaticProps() {
	const res = await fetch('http://localhost:3000/api/comics')
	const comics = await res.json()

	return {
		props: { comics },
		revalidate: 1,
	}
}
